[workspace]
resolver = "2"
members = [
    "crates/bitset", "crates/codegen",
    "crates/either",
    "crates/grammar",
    "crates/lexer",
    "crates/parsers", 
]
exclude = [
    "examples/ll1",
]
