[package]
name = "paresse-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.79", features = ["parsing", "printing", "full"] }
proc-macro2 = "1.0.88"
paresse-core = { path = "../paresse-core/" }

[lib]
proc-macro = true
